name: ac_posix_locale
description: POSIX locale related types
version: 0.1.1
repository: https://github.com/anthochamp/dart-posix-locale

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  ac_dart_essentials: ^0.2.1

dev_dependencies:
  ac_lints: ^0.4.0
  build_runner: ^2.3.3
  import_sorter: ^4.6.0
  test: ^1.24.2
