name: posix_locale
publish_to: 'none'
version: 1.0.0
repository: https://github.com/anthochamp/dart-posix-locale

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  anthochamp_dart_essentials:
    git: git@github.com:anthochamp/dart-essentials.git

dev_dependencies:
  anthochamp_lints:
    git: git@github.com:anthochamp/dart-lints.git
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  import_sorter: ^4.6.0
  lints: ^2.0.1
  test: ^1.24.2
