name: Validate Dart project

on: [ push, pull_request ]

jobs:
  lint:
    uses: anthochamp/dev-toolbox/.github/workflows/dart-lint.yml@9c751de1366fde227d30db685f40acc325c5f740
  test:
    uses: anthochamp/dev-toolbox/.github/workflows/dart-test.yml@9c751de1366fde227d30db685f40acc325c5f740
