name: Deploy Dart library

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  dart-validate:
    uses: anthochamp/dev-toolbox/.github/workflows/dart-validate.yml@cf8d20746895d6f353cbd936ff46f78086a60faf
  dart-publish:
    needs: dart-validate
    permissions:
      id-token: write
    uses: anthochamp/dev-toolbox/.github/workflows/dart-lib-publish.yml@cf8d20746895d6f353cbd936ff46f78086a60faf
